version: '3'

services:
  search_api:
    build: .
    command: 'python main.py'
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - redis

  redis:
    image: redis:6.0

  test:
    build: .
    command: 'pytest'
    volumes:
      - .:/app
